### ISSUE TITLE
Missing some fonts used in the svg logo

### ISSUE THREAD

**Issue by pfrazee** [DistributedCamp/2020#6] opened 2020-04-11 02:09 UTC
I seem to have the first font used ("Phosphate-Inline, Phosphate") though I don't know how widely available it is. I don't have the second font ("PressStart2P-Regular, 'Press Start 2P'"). It looks like this for me:

<img width="258" alt="Screen Shot 2020-04-10 at 9 09 26 PM" src="https://user-images.githubusercontent.com/1270099/79032898-946d5180-7b6f-11ea-847e-75cc6592b917.png">

**Comment by rdela** [comment] 2020-05-14 23:02
I think it makes sense to just use paths in the SVG and then either an alt tag or visually hidden element with the text “Distributed Camp 2020” vs trying to embed the font(s)?

Here is what it looks like on my iPhone, missing both fonts.

Initial load:

![image](https://user-images.githubusercontent.com/74381/81994183-20095080-95fc-11ea-85da-237e55455172.jpeg)

Dark theme/mode:

![image](https://user-images.githubusercontent.com/74381/81994229-3a432e80-95fc-11ea-9ed9-74efed66737a.jpeg)

**Comment by rdela** [comment] 2020-05-14 23:04
Press Start 2P on Google Fonts
https://fonts.google.com/specimen/Press+Start+2P

**Comment by alexwykoff** [comment] 2020-05-15 01:54
It's also possible to use png instead of svg or completely redesign the logo too!  
This is green field, so hoping for a lot of collaboration and creativity from anyone who wishes to participate.

**Comment by rdela** [comment] 2020-05-18 01:05
So we are discussing this on the #design channel [on discord](https://discord.gg/csZhgYY) but just to maximize reach, here is where we are. Come get involved on Discord: 
https://discord.gg/csZhgYY 

...or comment here if that is too much trouble.

So I found these National Park Service map symbols optimized for the web: https://github.com/nationalparkservice/symbol-library/
https://www.nps.gov/maps/tools/symbol-library/

And I made a version with the campground symbol. There is a [single campsite symbol](https://github.com/nationalparkservice/symbol-library/blob/gh-pages/src/standalone/campsite-black-30.svg
) too 
It would be little less busy but I like the multiple connotations for remote + parallelism etc
of [the campground one](https://github.com/nationalparkservice/symbol-library/blob/gh-pages/src/standalone/campground-black-30.svg).

After trying the symbol between the text, Dominic liked the version with the symbol above the text.

double hex (v2)

![distributed-camp-2020-black-2](https://user-images.githubusercontent.com/74381/82165116-a4f8a200-9868-11ea-9317-70d2c1c7a60d.png)
![distributed-camp-2020-white-2](https://user-images.githubusercontent.com/74381/82165119-a629cf00-9868-11ea-9d8b-0e08fc06da24.png)

Alex wrote:

> This is a really good direction you’re taking this!  fwiw I left an opening on the external shape to allow them to mesh with other hexagonal badges. 
> 
> Imagine if you replaced the content with other text like the name of a project or a title (participant, speaker, etc), can we place multiples of these and have them feel connected?

Then I made this one, open hex (v4)

![distributed-camp-2020-black-4](https://user-images.githubusercontent.com/74381/82165179-e0936c00-9868-11ea-8592-720a269b6ac2.png)
![distributed-camp-2020-white-4](https://user-images.githubusercontent.com/74381/82165180-e12c0280-9868-11ea-94f7-ae18da0ae50d.png)

All opinions welcome.

**Comment by rdela** [comment] 2020-05-18 01:13
I am aware of the (slightly off-)centering issue with Distributed, but the issue is with the font and I want to wait until everything else is final to make small adjustments like that.

**Comment by alexwykoff** [comment] 2020-05-28 05:04
This has since been fixed by https://github.com/DistributedCamp/2020/commit/e3833cf2995366a1e80b13b3e9bfd2842e2218a4

**Closed by alexwykoff** 2020-05-28 05:04 UTC
